development:
  adapter: redis
  url: redis://:b362022c-4968-4ce6-8521-6e2edd38b8b1@localhost:6379/1


test:
  adapter: async

production:
  adapter: redis
  url: redis://localhost:6379/1
  channel_prefix: procore_tutorial_production
